### ISSUE TITLE
character of separation

### ISSUE THREAD

**Issue by matth94** [FroggDev/zabbix-nfs#1]
Hello,  Is it normal that the character of separation is ";" instead of ":"?  line 73 of script frogg_nfs_check.sh :
# @param nfs share list separated with :
...
     SHARES=$(echo $2 | tr ";" "\n")

**Comment by FroggDev** [comment]
Hi,

When i made the script i choose ; as separators as you can see in the documentation :

`{$NFSSHARES} | the list of NFS shares that should be available, to set multiple shares they must be separated by ;`

Any specific point in using : instead of ; ?

Thanks

**Comment by matth94** [comment]
Ithank you for your return.
It’s good for me, my mistake comes from reading the test command of the readme :

To Test NFS share
./frogg_nfs_check.sh share 192.168.0.1 /nfsShare1:/nfsShare2:/nfsShare3

**Comment by FroggDev** [comment]
No worries in fact ./frogg_nfs_check.sh share 192.168.0.1 /nfsShare1:/nfsShare2:/nfsShare3 is to test it using command line (bash) cause the script can be used out of box, i understand that can be confusing cause syntax is not the same in macros
