### ISSUE TITLE
error: frogg_nfs_check.sh[share,{HOST.CONN},{$NFSSHARES}]" became not supported

### ISSUE THREAD

**Issue by vldanch** [FroggDev/zabbix-nfs#2]
@FroggDev An error occurs: `frogg_nfs_check.sh[share,{HOST.CONN},{$NFSSHARES}]" became not supported:
/usr/lib/zabbix/externalscripts/frogg_nfs_check.sh: [2] No such file or directory`
The file is in `/usr/lib/zabbix/externalscripts/`
He has rights 777...
What could be the problem?

**Comment by FroggDev** [comment]
Did you put it in **/usr/lib/zabbix/externalscripts/** of the zabbix server (not into the nfs server) ?
Did ou tried to launch the command out of box to test if it works : **./usr/lib/zabbix/externalscripts/frogg_nfs_check.sh version {NFS SERVER IP}** ?

**Comment by vldanch** [comment]
@FroggDev Solved the problem, it turns out if you use zabbix-proxy.service then you need to install this script on these hosts, and not on the main =))))
